### ISSUE TITLE
Add support for react-native 0.62

### ISSUE THREAD

**Issue by jacquesdev** [webraptor/react-native-deck-swiper#1]
Is it possible for someone to please add the required updates to make it work with rn0.62?

(@webraptor, I know you are already working on it)🥳

**Comment by webraptor** [comment]
[Indeed](https://github.com/webraptor/react-native-deck-swiper/projects/1#card-42719484)

Also contacted npm so that in the near future we'll be able to make new releases on the same package.

**Comment by gitschwifty** [comment]
What issues are you having on 0.62? I'm using RN 0.63 and not seeing any breaking issues, just warnings from Animated, and I believe my team member who implemented it originally was still on 0.62 when he did so. I could ask him to see if he had any issues or if he figured out a fix.

**Comment by jacquesdev** [comment]
@gitschwifty - it was based on this issue, https://github.com/alexbrillant/react-native-deck-swiper/issues/306. I did not actually try, just assumed it's an issue.

**Comment by gitschwifty** [comment]
I could throw together a repro to test it out but I'd like to hear from the people who reported it, the error they got could've easily been from something else & based on the trace I'm not sure it came from this package in the first place.

**Comment by Harin329** [comment]
I was on 0.62 a month ago and it was fine, updated to 0.63 and it's still good, only thing is the Animated warning as mentioned

**Comment by gitschwifty** [comment]
I'd mark this as needs more info and/or close this issue unless someone reports a current problem, not sure the people commenting in 306 will respond & I don't think it's an issue with this package.

**Comment by jacquesdev** [comment]
Agreed
