### ISSUE TITLE
Add testID prop

### ISSUE THREAD

**Issue by oikalyptus** [webraptor/react-native-deck-swiper#103]
Please add the possibility to set a testID.
I could submit a PR if you give me the permission.

**Comment by webraptor** [comment]
That would be awesome! We could put a general testId for the swiper and a dynamic one for each rendered card. But that can also be done through the card content. 

If you do submit a PR please also bump the patch version. 

Thanks

**Comment by oikalyptus** [comment]
Hey @webraptor,

My PR has been open for 3 weeks now. Let me know if you want me to change anything.
https://github.com/webraptor/react-native-deck-swiper/pull/104

**Comment by webraptor** [comment]
Completely forgot about it. Sorry.
