### ISSUE TITLE
Update prop-types Version | Severity: high

### ISSUE THREAD

**Issue by ebulku** [webraptor/react-native-deck-swiper#113]
node-fetch <=2.6.6
Severity: high

node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g

Will install react-native-deck-swiper@1.1.7, which is a breaking change
node_modules/isomorphic-fetch/node_modules/node-fetch
isomorphic-fetch 2.0.0 - 2.2.1
Depends on vulnerable versions of node-fetch
node_modules/isomorphic-fetch
fbjs 0.7.0 - 1.0.0
Depends on vulnerable versions of isomorphic-fetch
node_modules/react-native-deck-swiper/node_modules/fbjs
prop-types 15.5.0-alpha.0 - 15.6.1
Depends on vulnerable versions of fbjs
node_modules/react-native-deck-swiper/node_modules/prop-types
react-native-deck-swiper >=1.1.8
Depends on vulnerable versions of prop-types
node_modules/react-native-deck-swiper

**Comment by webraptor** [comment]
Please open a PR for this and bump the patch package version as well. Thanks!

**Comment by ebulku** [comment]
@webraptor I tried update it yesterday, but I had problems installing and running it locally.  Can you send some stable env you are using for development?

**Comment by webraptor** [comment]
I no longer actively work on the package :(
