### ISSUE TITLE
overlayLabels

### ISSUE THREAD

**Issue by samkhan016** [webraptor/react-native-deck-swiper#114]
I am able to show overlay images while swiping but i want to display the same when button is pressed. How can i do that as my screen lay out contains buttons at the bottom with which the user can swipe left or right but the overly does not display.

**Comment by nguyentruongson1604** [comment]
same

**Comment by Gabotron-ES** [comment]
Interested

**Comment by webraptor** [comment]
and enhancement would be needed for this as the labels show based on pan responder not the swipe transition animation. 

if a PR is opened I’ll gladly review / merge and release on npm
