### ISSUE TITLE
compatibility with Voiceover

### ISSUE THREAD

**Issue by tsgouros** [webraptor/react-native-deck-swiper#132]
This is an awesome package and we are using it happily. Our application is useful for blind and vision-impaired (BVI) users, and a user noticed that there are conventions associated with iOS Voiceover mode that are not honored by this package (three-finger swipes, e.g.) and that the voiceover seems to read three or four image titles at a time (reads the title of the top image, but also the next two or three). I don't know if the package is still under active development, but I think making it compatible with Voiceover would make it more widely useful to the BVI world. Thank you for the package and for considering adding this to your To-Do list.

**Comment by webraptor** [comment]
@tsgouros that sounds lovely. If you're using it in a BVI app, feel free to fork and create a PR against the repo. I'll be able to review and merge it once it's tested into the main package.

**Comment by tsgouros** [comment]
Will do, though the status is that this is among the fixes for our app for which we are currently seeking funding. Stay tuned.
