### ISSUE TITLE
Same npm install

### ISSUE THREAD

**Issue by Gabotron-ES** [webraptor/react-native-deck-swiper#133]
So I have a few questions, first is: why is the npm install same as original fork, how can I install thia one instead of original (unmantained?). Sorry for noob question.

Second, what are the differences between this fork and original one?

**Comment by webraptor** [comment]
original repo became unmaintained without any chance of release so npm package was switched to this one. this fork is the continuation of the original repo. PRs with bugfixes and enhancements against this repo are still published when needed on npm
