### ISSUE TITLE
Hope create a different repo instead of fork. So that others could npm directly. And also thanks for maintenance !! It really help

### ISSUE THREAD

**Issue by yhbyOff** [webraptor/react-native-deck-swiper#14]
thanks!

**Comment by webraptor** [comment]
We've already started the process in order to be able to publish on npm with the same package name.

**Comment by webraptor** [comment]
> thanks!

@yhbyOff Just [released a new version](https://www.npmjs.com/package/react-native-deck-swiper) under the same package name.
