### ISSUE TITLE
Doesn't Work With react-native-web

### ISSUE THREAD

**Issue by cmmouritsen** [webraptor/react-native-deck-swiper#15]
Thanks for taking over and updating this package. Please include this PR that should allow this package to be used with react-native-web projects: https://github.com/alexbrillant/react-native-deck-swiper/pull/263

**Comment by webraptor** [comment]
If the PR is against this repository I can take a look at it, but we cannot merge & release anything on the original repo.

**Comment by webraptor** [comment]
Fixed on [2.0.2-beta](https://github.com/webraptor/react-native-deck-swiper/releases/tag/2.0.2-beta)
