### ISSUE TITLE
Swipe does not work for android device. Same code work for IOS

### ISSUE THREAD

**Issue by yhbyOff** [webraptor/react-native-deck-swiper#18]
<Swiper
        cards={data}
        ref={(swiper) => {
          swipeRef.current = swiper;
        }}
        renderCard={renderHomeCard}
        onTapCard={_onTabCard}
        // no sure swipe is working on android or not, if not, check this place
        // this is a fix from https://github.com/alexbrillant/react-native-deck-swiper/issues/218
        // useViewOverflow={Platform.OS === "ios"}
        style={styles.swiperContainer}
        cardHorizontalMargin={0}
        cardIndex={0}
        backgroundColor="white"
        stackSize={1}
        onSwipedAll={onSwipedAllCards}
        swipeBackCard={true}
        animateOverlayLabelsOpacity
        disableBottomSwipe={true}
        onSwipedLeft={(index) => handleOnSwipeCard("left", index)}
        onSwipedRight={(index) => handleOnSwipeCard("right", index)}
        onSwipedTop={(index) => handleOnSwipeCard("top", index)}
/>

Code sample is above. Could you please help?

**Comment by yhbyOff** [comment]
it is no problem now. i started from anthor's example, and add new code step and step. Finally it works out!

**Comment by webraptor** [comment]
> it is no problem now. i started from anthor's example, and add new code step and step. Finally it works out!

glad to hear all good!
