### ISSUE TITLE
When stackSize=1, and using swipeBackCard, the card animation is overlap together when swipe back.

### ISSUE THREAD

**Issue by yhbyOff** [webraptor/react-native-deck-swiper#23]

**Comment by yhbyOff** [comment]
When swipe back, the current one will not disappear immediately. After the swiped card is back and override the existing one.
At this time, two cards are overlapped.

**Comment by webraptor** [comment]
That is actually the intended behaviour. The swipeBack method animates the card back on top of the deck. What you're describing is a deck of 1 card, sort of creating a paradox. The stackSize should be at least 2 for the swipeBack method. I've updated the readme to reflect this recommendation [here](https://github.com/webraptor/react-native-deck-swiper/pull/24)
