### ISSUE TITLE
Show overlay all along swipe transition

### ISSUE THREAD

**Issue by julien-maitan** [webraptor/react-native-deck-swiper#26]
When overlays are activated, they should be displayed whenever a swipe transition is running, not only on pan gesture. This would avoid screen flickering when releasing finger and provide a uniform behavior for swipe animations.
An example of expected behavior can be viewed in this app : https://play.google.com/store/apps/details?id=com.lemonde.morning&hl=fr

**Comment by maurocen** [comment]
Noticed this is missing. Would be nice to have (maybe have a prop to enable/disable this behavior?).

**Comment by michalpawlowski34** [comment]
🆙

**Comment by Gabotron-ES** [comment]
Up

**Comment by webraptor** [comment]
if someone opens a PR with the feature I’ll gladly merge it in and make a new release
