### ISSUE TITLE
Animated: useNativeDriver

### ISSUE THREAD

**Issue by d22ier** [webraptor/react-native-deck-swiper#27]
Hello, 
I updated expo from 36 to 39 and i had this error : 

_**WARN Animated: "useNativeDriver" was not specified. This is a required option and must be explicitly set to "true" or "false"**_

I searched on Google i found this issues : 
https://github.com/GeekyAnts/NativeBase/issues/3109

So i updated Swiper.js and added "useNativeDriver:false" to Animated.timing, Animated.spring and Animated.event. 

https://pastebin.com/Hxipk7Ez

It seems to be working well !

**Comment by webraptor** [comment]
This has already been fixed in [2.0.3-beta](https://github.com/webraptor/react-native-deck-swiper/releases/tag/2.0.3-beta), including latest release 2.0.5 

Make sure you have the latest version installed.
