### ISSUE TITLE
It is not rendering the second card

### ISSUE THREAD

**Issue by harrymash2006** [webraptor/react-native-deck-swiper#32]
Please help. After updating from 1.6.7 it is not showing second card.

I am using this code 

<Swiper
ref={swiper => {
this.swiper = swiper;
}}
cardStyle={this.getCardStyle}
inputRotationRange={[0, 0, 0]}
outputRotationRange={["0deg", "0deg", "0deg"]}
infinite={true}
onSwipedLeft={this._onSwipedRight}
onSwipedRight={this._onSwipedLeft}
cards={this.state.feeds}
renderCard={this._renderCard}
onSwipedTop={this._onSwiped}
onSwipedBottom={this._onSwipedBottom}
horizontalSwipe={this.state.horizontalSwipe}
verticalSwipe={(this.state.feeds.length >= 1 || this.state.verticalSwipe )?true:false}			
goBackToPreviousCardOnSwipeBottom={true}
onSwipedAll={this._onSwipedAll}
cardIndex={this.state.currentIndex}
backgroundColor={'#fff'}
keyExtractor={item => item.n_id}
cardVerticalMargin={0}
marginBottom={0}
horizontalThreshold={width/2}
cardHorizontalMargin={0}
onTapCard={this._ontapcard}
/>

and in _onSwiped function I am changing the value of currentIndex (cardIndex). Please help. After I swipe it is just showing blank screen.

**Comment by webraptor** [comment]
Please post a snack or something similar so that it is easy to reproduce your issue.

**Comment by harrymash2006** [comment]
Sorry, I think it was because of these values. It is working now after removing the below values
inputRotationRange={[0, 0, 0]}
outputRotationRange={["0deg", "0deg", "0deg"]}
