### ISSUE TITLE
Is it possible to swipe only in one direction at a time

### ISSUE THREAD

**Issue by harrymash2006** [webraptor/react-native-deck-swiper#34]
Is this possible to swipe only in one direction at a time than have a moving card in all directions ? Please have a look at this video to see what I mean. Is it possible to achieve something like in the video below ?

https://drive.google.com/file/d/1O4IMwM_n5mJ38nJ-u2dagcJsfy3uiyuH/view?usp=drivesdk

**Comment by harrymash2006** [comment]
@webraptor Please can you help ?

**Comment by webraptor** [comment]
You've got swipe animation props that can disable swiping in any direction. [Here's the link to the documentation](https://github.com/webraptor/react-native-deck-swiper#swipe-animation-props).
