### ISSUE TITLE
Push new items to the stack without re render

### ISSUE THREAD

**Issue by jaroslav009** [webraptor/react-native-deck-swiper#42]
Hello, I have a big deck so I need to download the files in batch.
What I'm downing is to download the first ten items and then after 5 swipes I start to download the other 5 an so one and pushing it to cardsData, the problem is that I can't add new data without break the app.

Is there a property like extraData in flat list that we can use?

Thanks

**Comment by jaroslav009** [comment]
I decided it. I just set stackSeparation={5} because this props was bigger

**Comment by Riaz5687** [comment]
i am facing same issue, could you please help me
