### ISSUE TITLE
Vertical scrollview now working

### ISSUE THREAD

**Issue by Surendiran1988** [webraptor/react-native-deck-swiper#56]
Hi Guys, I added `<Swiper/>` inside scrollview for me vertical scroll not working when scrolling on `<Swiper>`. Anyone help me to resolve the issue.

Thanks :)

```
<ScrollView>
<Swiper/>
</ScrollView>
```

**Comment by webraptor** [comment]
https://github.com/webraptor/react-native-deck-swiper/issues/22
