### ISSUE TITLE
ScrollView inside card

### ISSUE THREAD

**Issue by haveamission** [webraptor/react-native-deck-swiper#63]
Is it possible to have a ScrollView that works inside a card?

I want to essentially have my arbitrary card, let me give a toy example:

```
<View>
...contents
</View>
```

And among those contents, I want to have a `<ScrollView />` that scrolls. Right now when I try to scroll on the scrollview, I can't, it just drags the card.

**Comment by thekundan2022** [comment]
Hi. Have you got any solutions for this..?

**Comment by haveamission** [comment]
So as far as I can tell, I just put this into the ScrollView (and also the child View, but I don't think that was necessary):

```
              onStartShouldSetResponder={() => true}
              onTouchEnd={e => {
                e.stopPropagation();
              }}
```

Let me know if that helps

**Comment by webraptor** [comment]
https://github.com/webraptor/react-native-deck-swiper/issues/22
