### ISSUE TITLE
Console warning - deprecated method

### ISSUE THREAD

**Issue by matapo** [webraptor/react-native-deck-swiper#74]
There is a warning on replacing a screen with swiper component. Should I create a PR? 

<img src="https://user-images.githubusercontent.com/26110566/180052671-a400329a-af1c-4f1a-8f84-adad553edc25.png" alt="Your image title" width="400"/>

**Comment by webraptor** [comment]
Yeah. That would be helpful

**Comment by matapo** [comment]
> Yeah. That would be helpful

#75 have a look - was a small change

**Comment by matapo** [comment]
was resolved with #75
