### ISSUE TITLE
variable not found componentWillUnmountAfterInteractions

### ISSUE THREAD

**Issue by damianstone** [webraptor/react-native-deck-swiper#86]
Just need to add this.componentWillUnmountAfterInteractions in swiper.js when call it from componentWillUnmount

**Comment by webraptor** [comment]
I’d be awesome if you can open a PR with it

**Comment by nofacez** [comment]
https://github.com/webraptor/react-native-deck-swiper/pull/87

**Comment by webraptor** [comment]
Fixed on 2.0.11
