### ISSUE TITLE
setting VerticalSwipe = false causes an issue

### ISSUE THREAD

**Issue by danielha0221** [webraptor/react-native-deck-swiper#9]
` <>
        <View style={styles.container}>
          <Swiper
            cards={['DO', 'MORE', 'OF', 'WHAT', 'MAKES', 'YOU', 'HAPPY']}
            renderCard={(card) => {
              return (
                <View style={styles.card}>
                  <Text style={styles.text}>{card}</Text>
                </View>
              );
            }}
            onSwiped={(cardIndex) => {
              console.log(cardIndex);
            }}
            onSwipedAll={() => {
              console.log('onSwipedAll');
            }}
            cardIndex={0}
            verticalSwipe={false}
            backgroundColor={'#4FD0E9'}
            stackSize={3}>
            <Button
              onPress={() => {
                console.log('oulala');
              }}
              title="Press me">
              You can press me
            </Button>
          </Swiper>
        </View>
      </>`

following error is occurred when setting verticalSwipe={false}.

"Invariant Violation: Bad mapping of type number for key dy, event value must map to AnimatedValue"

By the way, thank you for your decision to keep taking care of this repo.

**Comment by webraptor** [comment]
This has been [fixed over here](https://github.com/webraptor/react-native-deck-swiper/pull/7), version 1.7.1, but we can't yet make NPM release, so you'd have to use the branch to install the package until npm release is possible.
